# Generated by Django 4.1 on 2023-07-14 09:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Makers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'メーカー',
                'db_table': 'makers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='部品名')),
                ('product_number', models.CharField(max_length=255, verbose_name='品番')),
                ('max_inventory', models.IntegerField(verbose_name='最大在庫数')),
                ('min_inventory', models.IntegerField(verbose_name='最小在庫数')),
                ('inventory', models.IntegerField(default=0, verbose_name='在庫数')),
                ('reset', models.IntegerField(choices=[(1, 'リセット'), (2, '-')], default=2, verbose_name='リセット')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.categories', verbose_name='カテゴリー')),
                ('makers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.makers', verbose_name='メーカー')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '在庫部品',
                'db_table': 'product',
            },
        ),
    ]
